### ISSUE TITLE
vt decompose adjust counts for ref, alt, dp in genotypes

### ISSUE THREAD

**Issue by brentp** [atks/vt#11]
GATK uses AD=ref,alt1,alt2...
freebayes uses RO=ref, AO=alt1,alt2

it would be nice if these were pulled when doing the decompose (and then used to recalc DP) so that they could be used downstream to derive allele frequency, etc.

**Comment by brentp** [comment]
As an example, consider the variant:

    20  212674  .   A   AAAAT,AAAATAAATAAAT,AAAATAAAT   15721.23    PASS    AC=1,1,0;AF=0.500,0.500,0.00;AN=2;BaseQRankSum=0.619;ClippingRankSum=-5.790e-01;DP=15;FS=2.115;GQ_MEAN=198.41;GQ_STDDEV=151.16;InbreedingCoeff=-0.0059;MQ=60.00;MQ0=0;MQRankSum=-2.480e-01;NCC=0;QD=22.51;ReadPosRankSum=0.810;SOR=0.448;VQSLOD=2.29;culprit=FS;set=Intersection    GT:AD:DP:GQ:PL  1/2:0,6,9,0:15:99:663,379,358,254,0,226,631,377,252,629 

Split out, the fields of interest are:


    GT 1/2
    AD 0,6,9,0
    DP 15

We have been prototyping our own tool and comparing to vt (which we'd prefer to use) below shows the output for each tool on the 3 decomposed variants:

    CH  POS     ALT             VT_FMT      VT_GT               GEMIN_FMT       GEMINI_GT
    20  212674  AAAAT           GT:DP:PL    1/.:15:663,379,358  GT:AD:GQ:PL:DP     1/.:0,6:99:663,379,358:6
20  212674  AAAATAAAT       GT:DP:PL    ./.:15:663,631,629  GT:AD:GQ:PL:DP  ./.:0,0:99:663,631,629:0
20  212674  AAAATAAATAAAT   GT:DP:PL    ./1:15:663,254,226  GT:AD:GQ:PL:DP  ./1:0,9:99:663,254,226:9

**Comment by atks** [comment]
when you run decompose, use the -s option.  It's actually experimentally and is supposed to print out any field that is of counts R, A or G.  do try it and let me know if there are any bugs.

**Comment by brentp** [comment]
@atks , I re-ran with -s and it includes the additional fields, but they are unchanged. e.g. AD remains as 0,6,9,0

**Comment by atks** [comment]
Can you email me the vcf file at atks@umich.edu?

**Comment by atks** [comment]
The problem is that in the header, AD's Number was not listed as R.  In VCF 4.2, it now has a count of R that means it has the same number of values as the total number of alleles including reference.

A quick solution here is to edit the header, if it is too cumbersome to do that, you can try the alternate header trick described here: http://genome.sph.umich.edu/wiki/Vt#Alternate_headers

**Comment by brentp** [comment]
The freebayes version use Number=A, but I get a segfault when running with `-s`.

**Comment by ekg** [comment]
Just following this and I think it's awesome!

**Comment by atks** [comment]
@brentp Can you do a git pull and try again?  It was an issue with type recognition.  The output works, but maybe the handling of missing fields is not the best possible.  I'll try and find a better solution later.

@ekg hey Erik! Hope you are having a great time at Sanger!  say, did you managed to solve https://github.com/ekg/freebayes/issues/97 yet?

**Comment by arq5x** [comment]
Thansk for looking into this.  Quick question: any idea why allele depths don't have a standard in the VCF spec?  Seems like it would solve a lot of troule like this, especially since it is such a fundmental attribute.

**Comment by atks** [comment]
It's definitely a nice attribute to have to accompany the genotype likelihoods and genotypes.
You might want to raise this question at https://github.com/samtools/hts-specs.

**Comment by brentp** [comment]
@atks . Thanks! Looks like it's adjusting AO, RO correctly.
Any chance of setting DP to AO + RO? or AD[1] + AD[0]? Could be an optional flag?

**Comment by atks** [comment]
That requires pre-knowledge on the nature of AO/RO and AD, so I will not be implementing that, this will have to be resolved downstream in other scripts.

Another reason is that DP is supposed to be the read depth at that locus, not the sum of relevant reads pertaining to the described alleles.  If an allele is present that is not described, I think the read should be marked as ambiguous or as other allele.  The current output will allow you to handle undescribed variants in the decomposed biallelic record appropriately.

The purpose of decompose was actually to facilitate the comparison of discovered alleles between variant sets, the support for genotype fields decomposition was for the purpose of retaining the partial genotypes that allows one to perform genotype comparisons even across decomposed alleles.

**Comment by brentp** [comment]
Fair enough. I think as a stop-gap, we can propose to sed or otherwise alter the GATK header so that Number=R for AD.

**Comment by atks** [comment]
@brentp  weird missing values output for decompose fixed.  please let me know if you see any weird things.
