### ISSUE TITLE
non-termination for specific vcf

### ISSUE THREAD

**Issue by brentp** [atks/vt#12]
with this VCF:
     wget https://s3.amazonaws.com/biodata/variants/cosmic-v68-GRCh37.vcf.gz

this command:
```Shell
   vt decompose  cosmic-v68-GRCh37.vcf.gz   \
          | vt normalize -r /data/human/b37/human_g1k_v37_decoy.fasta - > vv.vcf
```
puts some data in the output, but then it stalls after 77K lines or so.

**Comment by atks** [comment]
There's a record with a missing ALT, vt thinks it could be normalized and ends up looping endlessly trying to left align it.  Fixed.  Now, such reference records will be ignored.

You can see that the VCF has 42 reference records via vt peek cosmic-v68-GRCh37.vcf.gz

**Comment by brentp** [comment]
Aye, fixed. Thanks!
