### ISSUE TITLE
vt decompose -s for Type=String

### ISSUE THREAD

**Issue by brentp** [atks/vt#13]
Is this not supported because there could be unrelated commas in the value?
Could decompose support splitting when Type=String?

You can see an example VCF of this here:
ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar_20150305.vcf.gz

where the INFO fields starting with "CLN" have comma separated values with multiple alts.

We have adjusted the header to set Number=A for INFO's we want to split.

**Comment by atks** [comment]
May I know what's the error?  I can run decompose with -s option on it.
There are no genotype fields in the example.

**Comment by brentp** [comment]
there's no error, it just doesn't split the field.

**Comment by brentp** [comment]
I saw that it skips that case in the code. e.g.: https://github.com/atks/vt/blob/master/decompose.cpp#L476

**Comment by atks** [comment]
I did not implement it for the info fields yet, I'll get it done by
tomorrow. Sorry about that.

**Comment by brentp** [comment]
thankyou! here's a VCF for testing: https://gist.githubusercontent.com/brentp/a4d82c4f017a32fe4462/raw/40841dabe7a4178515bab6125f8628daba31147a/ex.vcf

**Comment by brentp** [comment]
although that VCF might not be well formatted. Sometimes the CLN fields for variants with mutliple alts don't match Number=A.

**Comment by atks** [comment]
this will take a bit more time, I need htslib to fix an API.

**Comment by ekg** [comment]
What's the bug against htslib?

**Comment by atks** [comment]
not a bug, I'm just requesting that their bcf_get_info_string() return an array of strings like what bcf_get_format_string() does.  Current bcf_get_infor_string() just returns a single string even if it is actually a list of strings delimited by ",".

**Comment by atks** [comment]
@brentp  please pull and try.  for cases where there are less than expected values, decompose will discard the info field for decomposed alleles that are more than the number of records and for those where there are more than expected values, decompose will discard the extraneous values.

**Comment by brentp** [comment]
sorry for the late reply. this works as expected I think. We had to special-case the clinvar dataset since it uses some non-standard stuff, but the vt part was fine as far as I could see.
thanks.
