### ISSUE TITLE
vt cat results in chrom replacement

### ISSUE THREAD

**Issue by cboustred** [atks/vt#14]
Hi,

Thanks for developing vt - looks like it could be really helpful

I've come across an issue when using vt cat to combine VCF files generated on the same set of samples but on different chromosomes (as per the example in the docs: http://genome.sph.umich.edu/wiki/Vt#Concatenate). The chromosome name is being replaced with whatever it is in the first VCF file supplied. I've tried with both specifying the VCFs in full or using an input file list (-L)

An example of what I'm trying to do:

vt cat chr1.vcf chr2.vcf -o cat.vcf

The variants are concatenated in cat.vcf, however all the chromosome names would be converted to chr1 

BW

Chris

**Comment by atks** [comment]
vt cat just writes out the header in the first vcf file in the list.  To ensure a complete header, you can prepare a complete header with all the contigs and necessary meta information and name it as chr1.vcf.hdr.  vt will read that header instead and print that out in the out file.  

It would be if vt scans through all the headers but I prefer to keep the implementation simple as that solution does not work in a series of pipes.

Did you try bcftools concat too?

**Comment by cboustred** [comment]
Hi, thanks for getting back to me so quickly, bcftools concat is just what I needed!

Thanks again,

Chris

**Comment by atks** [comment]
fixed. allows for concatenating of files with different headers.  missing headers in the first file are copied over and ids are translated accordingly.  checks for consistency of samples in all the files too. Used bcf_hdr_combine and bcf_translate which made it really simple.
