### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jdh237** [atks/vt#17]
I am trying to use 'vt decompose' to decompose variants from a large VCF file (~80G compressed). When I use the '-s' option, the RAM usage grows to very high levels. It appears to roughly track the size of the uncompressed input file read to that point. I don't see the problem running 'vt decompose' without the -s option. I have started trying to track down the source, but haven't found it yet.

Your help would be much appreciated. Thanks.

-Jason

**Comment by atks** [comment]
Is there anyway you can link me to your file?

**Comment by jdh237** [comment]
Not these specific VCF files. I'd think you should be able to reproduce the effect with any big VCF file though. Maybe something from 1000 Genomes phase 3? The key clue, I think, is the fact that the same file processed without the -s flag uses a constant low level of RAM.

-Jason

**Comment by atks** [comment]
can you try the updated version?

**Comment by jdh237** [comment]
So far so good. Memory usage is low and steady, no errors yet. Thanks for the quick fix!

-Jason

**Comment by atks** [comment]
Let me know if there is still an issue, the implementation is not good, I'm just patching it.  Will recode it properly eventually.
