### ISSUE TITLE
Reference genome file for vt normalize

### ISSUE THREAD

**Issue by tfarrah** [atks/vt#18]
I cannot find any documentation on what is expected for the reference fasta file for vt normalize (the -r option).

I tried using the hs37d5.fa file provided with your resource bundle. However, I get the following error:
[variant_manip.cpp:637 right_trim_or_left_extend] failure to extract base from fasta file: chr1:825765

I also tried concatenating the UCSC files for chromosomes 1-22, X, Y, and M. This gave me the same error but at a later point in the file:
[variant_manip.cpp:637 right_trim_or_left_extend] failure to extract base from fasta file: chr19:423687

My command line:
vt normalize -r hs37d5.fa Genotype.vcf.gz -o Genotype.vt.normalized.vcf

I can't share the entire input file because it is sensitive. However, I get the same error with a tiny input file containing the problem record:

##fileformat=VCFv4.1
##reference=ftp://ftp.completegenomics.com/ReferenceFiles/build37.fa.bz2
##contig=<ID=1,length=249250621,assembly=B37,md5=1b22b98cdeb4a9304cb5d48026a85128,species="Homo sapiens">
##contig=<ID=19,length=59128983,assembly=B37,md5=1aacd71f30db8e561810913e0b72636d,species="Homo sapiens">
##ALT=<ID=CGA_NOCALL,Description="No-called record">
##ALT=<ID=INS:ME:ALU,Description="Insertion of ALU element">
##ALT=<ID=INS:ME:L1,Description="Insertion of L1 element">
##ALT=<ID=INS:ME:SVA,Description="Insertion of SVA element">
##ALT=<ID=INS:ME:MER,Description="Insertion of MER element">
##ALT=<ID=INS:ME:LTR,Description="Insertion of LTR element">
##ALT=<ID=INS:ME:PolyA,Description="Insertion of PolyA element">
##ALT=<ID=INS:ME:HERV,Description="Insertion of HERV element">
##FILTER=<ID=VQLOW,Description="Call is homozygous and the varScoreVAF is less than 20dB, or the call is not homozygous and the varScoreVAF is less than 40dB">
##FILTER=<ID=SQLOW,Description="Somatic variant has somaticScore < -10">
##FILTER=<ID=FET30,Description="Fisher somatic score < 30">
##FILTER=<ID=AMBIGUOUS,Description="Read evidence does not strongly distinguish multiple non-reference candidate alleles">
##FILTER=<ID=URR,Description="Too close to an underrepresented repeat">
##FILTER=<ID=MPCBT,Description="Mate pair count below 10">
##FILTER=<ID=SHORT,Description="Junction side length below 70">
##FILTER=<ID=TSNR,Description="Transition sequence not resolved">
##FILTER=<ID=INTERBL,Description="Interchromosomal junction in baseline">
##FILTER=<ID=sns75,Description="Sensitivity to known MEI calls in range (.75,.95] i.e. medium FDR">
##FILTER=<ID=sns95,Description="Sensitivity to known MEI calls in range (.95,1.00] i.e. high to very high FDR">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele">
##INFO=<ID=CGA_XR,Number=A,Type=String,Description="Per-ALT external database reference (dbSNP, COSMIC, etc)">
##INFO=<ID=AF,Number=A,Type=String,Description="Allele frequency, or &-separated frequencies for complex variants (in latter, '?' designates unknown parts)">
##INFO=<ID=CGA_FI,Number=A,Type=String,Description="Functional impact annotation">
##INFO=<ID=CGA_PFAM,Number=.,Type=String,Description="PFAM Domain">
##INFO=<ID=CGA_MIRB,Number=.,Type=String,Description="miRBaseId">
##INFO=<ID=CGA_RPT,Number=.,Type=String,Description="repeatMasker overlap information">
##INFO=<ID=CGA_SDO,Number=1,Type=Integer,Description="Number of distinct segmental duplications that overlap this locus">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=CGA_WINEND,Number=1,Type=Integer,Description="End of coverage window">
##INFO=<ID=CGA_BF,Number=1,Type=Float,Description="Frequency in baseline">
##INFO=<ID=CGA_MEDEL,Number=4,Type=String,Description="Consistent with deletion of mobile element; type,chromosome,start,end">
##INFO=<ID=MATEID,Number=1,Type=String,Description="ID of mate breakend">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=CGA_BNDG,Number=A,Type=String,Description="Transcript name and strand of genes containing breakend">
##INFO=<ID=CGA_BNDGO,Number=A,Type=String,Description="Transcript name and strand of genes containing mate breakend">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=MEINFO,Number=4,Type=String,Description="Mobile element info of the form NAME,START,END,POLARITY">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phase Set">
##FORMAT=<ID=SS,Number=1,Type=String,Description="Somatic Status: Germline, Somatic, LOH, or . (Unknown)">
##FORMAT=<ID=FT,Number=1,Type=String,Description="Genotype filters">
##FORMAT=<ID=CGA_ALTCALLS,Number=2,Type=String,Description="Alternative call sequences and scores">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FORMAT=<ID=EHQ,Number=2,Type=Integer,Description="Haplotype Quality, Equal Allele Fraction Assumption">
##FORMAT=<ID=CGA_CEHQ,Number=2,Type=Integer,Description="Calibrated Haplotype Quality, Equal Allele Fraction Assumption">
##FORMAT=<ID=GL,Number=.,Type=Integer,Description="Genotype Likelihood">
##FORMAT=<ID=CGA_CEGL,Number=.,Type=Integer,Description="Calibrated Genotype Likelihood, Equal Allele Fraction Assumption">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Read Depth">
##FORMAT=<ID=AD,Number=2,Type=Integer,Description="Allelic depths (number of reads in each observed allele)">
##FORMAT=<ID=CGA_RDP,Number=1,Type=Integer,Description="Number of reads observed supporting the reference allele">
##FORMAT=<ID=CGA_GP,Number=1,Type=Float,Description="Depth of coverage for 2k window GC normalized to mean">
##FORMAT=<ID=CGA_NP,Number=1,Type=Float,Description="Coverage for 2k window, GC-corrected and normalized relative to copy-number-corrected multi-sample baseline">
##FORMAT=<ID=CGA_CL,Number=1,Type=Float,Description="Nondiploid-model called level">
##FORMAT=<ID=CGA_LS,Number=1,Type=Integer,Description="Nondiploid-model called level score">
##FORMAT=<ID=CGA_CP,Number=1,Type=Integer,Description="Diploid-model called ploidy">
##FORMAT=<ID=CGA_PS,Number=1,Type=Integer,Description="Diploid-model called ploidy score">
##FORMAT=<ID=CGA_CT,Number=1,Type=String,Description="Diploid-model CNV type">
##FORMAT=<ID=CGA_TS,Number=1,Type=Integer,Description="Diploid-model CNV type score">
##FORMAT=<ID=CGA_BNDMPC,Number=1,Type=Integer,Description="Mate pair count supporting breakend">
##FORMAT=<ID=CGA_BNDPOS,Number=1,Type=Integer,Description="Breakend position">
##FORMAT=<ID=CGA_BNDDEF,Number=1,Type=String,Description="Breakend definition">
##FORMAT=<ID=CGA_BNDP,Number=1,Type=String,Description="Precision of breakend">
##FORMAT=<ID=CGA_IS,Number=1,Type=Float,Description="MEI InsertionScore: confidence in occurrence of an insertion">
##FORMAT=<ID=CGA_IDC,Number=1,Type=Float,Description="MEI InsertionDnbCount: count of paired ends supporting insertion">
##FORMAT=<ID=CGA_IDCL,Number=1,Type=Float,Description="MEI InsertionLeftDnbCount: count of paired ends supporting insertion on 5' end of insertion point">
##FORMAT=<ID=CGA_IDCR,Number=1,Type=Float,Description="MEI InsertionRightDnbCount: count of paired ends supporting insertion on 3' end of insertion point">
##FORMAT=<ID=CGA_RDC,Number=1,Type=Integer,Description="MEI ReferenceDnbCount: count of paired ends supporting reference allele">
##FORMAT=<ID=CGA_NBET,Number=1,Type=String,Description="MEI NextBestElementType: (sub)type of second-most-likely inserted mobile element">
##FORMAT=<ID=CGA_ETS,Number=1,Type=Float,Description="MEI ElementTypeScore: confidence that insertion is of type indicated by CGA_ET/ElementType">
##FORMAT=<ID=CGA_KES,Number=1,Type=Float,Description="MEI KnownEventSensitivityForInsertionScore: fraction of known MEI insertion polymorphisms called for this sample with CGA_IS at least as high as for the current call">
chr1    825681  .       AGGCGTGAGCCACTGCACCCGGCCTTGACTTC        .       .       nc      END=825712      GT      .
chr1    825742  .       ACAAGGGGGTTCT   .       .       nc      END=825754      GT      .
chr1    825767  GS000007651-ASM_1860_L  C       ]1:5726936]C    .       PASS    NS=1;SVTYPE=BND;MATEID=GS000007651-ASM_1860_R;CGA_BF=0.92       GT      1
chr1    825796  .       CAGCCTGAGTGACAGAGTGAG   .       .       nc      END=825816      GT      .
chr1    825826  .       C       .       .       nc      END=825826      GT      .
chr19   423506  .       CTCGCTC .       .       nc      END=423512      GT      .
chr19   423541  .       TCCTGGGGGGTCCTCCCCCCCT  .       .       nc      END=423562      GT      .
chr19   423689  GS000007651-ASM_2163_R  C       ]19:423261]C    .       PASS    NS=1;SVTYPE=BND;MATEID=GS000007651-ASM_2163_L;CGA_BF=0.75;CGA_XR=rs72175445;CGA_BNDG=NM_012435|-;CGA_BNDGO=NM_012435|-     GT      1
chr19   425290  rs73916977      G       A       .       PASS    NS=1;AN=2;AC=1;CGA_XR=dbsnp.130|rs73916977;CGA_FI=25759|NM_012435.2|SHC2|INTRON|UNKNOWN-INC
        GT:GQ:HQ:EHQ    1/0:400:400,400:398,398
chr19   426030  .       A       .       .       nc      END=426030      GT      .

Many thanks for any insight you can provide!

**Comment by tfarrah** [comment]
I tried running vt validate on the tiny VCF I posted above;

 vt validate tiny.vcf.gz -r hs37d5.fa
validate v0.5

options:     input VCF file        tiny.vcf.gz
         [r] reference FASTA file  hs37d5.fa

Segmentation fault

**Comment by atks** [comment]
Hi Terry,

hs37d5's chromosomes are labeled as 1,2,3 ... without the chr.  Your vcf has chr1 instead of 1.  You have to use a fasta file that was used to generate your vcf file.

**Comment by tfarrah** [comment]
Ah! Thank you.
