### ISSUE TITLE
-i option does not have effect

### ISSUE THREAD

**Issue by nekrut** [atks/vt#19]
It appears that using the -i option does not have any effect of the size and content of output file using `vt normalize` compiled from 0d5345007825e25a62013ef3c37fb8a43bbbe265:

`-i "22:20000000-21000000,22:10000000-11000000" ` and a run without `-i` produces exactly the same output

**Comment by atks** [comment]
Can you try that again without the inverted commas?

-i 22:20000000-21000000,22:10000000-11000000

**Comment by nekrut** [comment]
inverted commas are a part of github md formatting. The actual command was without them

**Comment by atks** [comment]
I tried it on a VCF file and it worked fine,  can you link me to your VCF file?

**Comment by nekrut** [comment]
it is VCF version of ftp://share.sph.umich.edu/vt/grch37/NA12878.illumina.platinum.snps.indels.complex.sites.bcf

**Comment by nekrut** [comment]
vcf was generated using `bcftools view <file_name> 20`

**Comment by atks** [comment]
bcftools view <file_name> 20  extracts all records from chromosome 20, so if you extract regions from chromosome 22, there will be nothing - just the header.

**Comment by nekrut** [comment]
i used 22 (typo in my post)

**Comment by atks** [comment]
I still cannot reproduce the error.  Can you show all the commands you used?

bcftools view  NA12878.illumina.platinum.snps.indels.complex.sites.bcf 22 -O b -o 22.bcf
vt index 22.bcf
vt view 22.bcf -i 22:20000000-21000000,22:10000000-11000000 -o a.bcf
vt view 22.bcf  -o b.bcf
ls -lh a.bcf b.bcf 
-rw-r--r-- 1 atks statgen-users  13K Apr 22 20:40 a.bcf
-rw-r--r-- 1 atks statgen-users 471K Apr 22 20:40 b.bcf

**Comment by nekrut** [comment]
But try to do this on unindexed vcf instead.

**Comment by nekrut** [comment]
e.g., 

`bcftools view NA12878.illumina.platinum.snps.indels.complex.sites.bcf -o 22.vcf
antons-macbook-air:vt_bundle_hg37 anton$ vt view 22.vcf -o b.vcf
antons-macbook-air:vt_bundle_hg37 anton$ vt view 22.vcf -i 22:20000000-21000000,22:10000000-11000000 -o a.vcf
antons-macbook-air:vt_bundle_hg37 anton$ ls -lh a.vcf b.vcf 
-rw-r--r--  1 anton  staff   315M Apr 23 14:29 a.vcf
-rw-r--r--  1 anton  staff   315M Apr 23 14:29 b.vcf`

**Comment by nekrut** [comment]
I should instead throw an error that the file is not indexed, no?

**Comment by atks** [comment]
yes it should throw an error.  my version throws 
[E:BCFOrderedReader] index cannot be loaded for 22.vcf for random access

I don't know why does yours not return an error.

**Comment by atks** [comment]
Do you have any environmental setting that is redirecting stderr?

**Comment by atks** [comment]
Can you do a pull and try again?

I realized that I accidentally saved 22.vcf as a bcf file so I was unable to replicate the problem.

**Comment by nekrut** [comment]
building...

**Comment by nekrut** [comment]
yep:

`[E:BCFOrderedReader] no random access support for VCF file: 22.vcf`

Thanks!

**Comment by atks** [comment]
great, thanks for reporting the issue.  

building with make -j 100 will make it much faster.
