### ISSUE TITLE
make fails with missing #include pregex.h

### ISSUE THREAD

**Issue by mjsduncan** [atks/vt#29]
hi, on a current ubuntu 14.04 i am getting this error with the latest pull:

g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2  -D__STDC_LIMIT_MACROS -o annotate_1000g.o -c annotate_1000g.cpp
In file included from annotate_1000g.h:36:0,
                 from annotate_1000g.cpp:24:
filter.h:30:20: fatal error: pregex.h: No such file or directory
 #include "pregex.h"
                    ^
compilation terminated.
make: *** [annotate_1000g.o] Error 1

googling and dpkg don't turn up anything for "pregex.h", is it a typo?

thanks for all your work.

mike d

**Comment by atks** [comment]
please try again.  I added support for regular expression matching in vt filter expressions and forgot to add the relevant files.  Fixed now.

**Comment by mjsduncan** [comment]
compiles now, thanks!
