### ISSUE TITLE
ID field empty

### ISSUE THREAD

**Issue by brentp** [atks/vt#30]
in recent version, when running decompose and normalize, the header gets these lines:

```
##INFO=<ID=,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##INFO=<ID=OLD_VARIANT,Number=.,Type=String,Description="Original chr:pos:ref:alt encoding">
```
The former, without an ID, causes problems in downstream parsers.

I'm running as:
```
vt decompose -s $VCF   | vt normalize -r $REF - 
```

**Comment by atks** [comment]
can I have an example VCF file?

**Comment by atks** [comment]
please pull and try again.  sorry about that bug.

**Comment by brentp** [comment]
Thanks! was just about to send VCF. this fixes it.
