### ISSUE TITLE
Problem with sorting COSMIC

### ISSUE THREAD

**Issue by holtgrewe** [atks/vt#32]
The following fails reproducably on COSMIC v72 (available after registration from http://cancer.sanger.ac.uk/cosmic) on the current version.

```
vt cat CosmicNonCodingVariants.normalized.vcf.gz CosmicCodingMuts.normalized.vcf.gz \
        | vt sort /dev/stdin -o out.vcf.gz
```

**Comment by atks** [comment]
I downloaded the files but I cannot reproduce the error.  The sorting went fine.

The VCF files I had bgzipped them, then I indexed them.

Can you send me the error message you encountered?

**Comment by atks** [comment]
@holtgrewe

I tried contacting you about this issue, but it seems like there is no response, so I assume all is well now and I am closing this issue.  If there are still any problems, feel free to open this again.
