### ISSUE TITLE
Header parsing bug leads to missing VCF columns in output

### ISSUE THREAD

**Issue by trutane** [atks/vt#33]
A header line containing extra whitespace outside of the "<...>" content can lead to missing VCF columns in the output. Here's an example input VCF containing a header line line with about 60 trailing space characters in the last FILTER header line, right before the first FORMAT line. This will look like a blank line in this window; scroll all the way right to see the newline quote character:

**Input VCF file contents:**

    ##fileformat=VCFv4.1
    ##fileDate=20150126
    ##reference=hs37d5
    ##phasing=partial
    ##FILTER=<ID=INDEL_SPECIFIC_FILTERS,Description="QD < 2.0 || ReadPosRankSum < -20.0 || InbreedingCoeff < -0.8 || FS > 200.0">
    ##FILTER=<ID=LowQual,Description="Low quality">
    ##FILTER=<ID=VQSRTrancheSNP99.00to99.90,Description="Truth sensitivity tranche level for SNP model at VQS Lod: -6.6778 <= x < -0.6832">
    ##FILTER=<ID=VQSRTrancheSNP99.90to100.00+,Description="Truth sensitivity tranche level for SNP model at VQS Lod < -36469.5723">
    ##FILTER=<ID=VQSRTrancheSNP99.90to100.00,Description="Truth sensitivity tranche level for SNP model at VQS Lod: -36469.5723 <= x < -6.6778">                 \
                                             
    ##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
    ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
    ##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
    ##FORMAT=<ID=GATK,Number=1,Type=String,Description="Genotype as called by GATK. Always a diploid call. All other genotype stats based on this genotype.">
    ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype after Personalis post-processing to match detected chromosome counts.">
    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA00001
    1       12065947        PTV001  C       T,A     29      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:19
    1       109817590       PTV002  G       T       77      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:20
    1       153791300       PTV003  CTG     C       81      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:21
    1       156104666       PTV004  TTGAGAGCCGGCTGGCGGAT    TCC     30      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:22
    1       156108541       PTV005  G       GG      31      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:23
    1       161279695       PTV006  T       C,A     32      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:24
    1       169519049       PTV007  T       .       35      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:24
    1       226125468       PTV097  G       A       99      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:109
    16      2103394 PTV056  C       T       68      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:72
    4       31789170        PTV021  G       .       77      PASS    .       GT:GATK:AD:DP:GQ        0/1:0/1:3,2:5:38

**Output VCF file data:**
Two of the variants in this input get normalized, and vt terminates normally. However, the output VCF is lacking the FORMAT and genotype columns:

    #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
    1       12065947        PTV001  C       T,A     29      PASS    .
    1       109817590       PTV002  G       T       77      PASS    .
    1       153791300       PTV003  CTG     C       81      PASS    .
    1       156104667       PTV004  TGAGAGCCGGCTGGCGGAT     CC      30      PASS    OLD_VARIANT=1:156104666:TTGAGAGCCGGCTGGCGGAT/TCC
    1       156108540       PTV005  C       CG      31      PASS    OLD_VARIANT=1:156108541:G/GG
    1       161279695       PTV006  T       C,A     32      PASS    .
    1       169519049       PTV007  T       .       35      PASS    .
    1       226125468       PTV097  G       A       99      PASS    .
    16      2103394 PTV056  C       T       68      PASS    .
    4       31789170        PTV021  G       .       77      PASS    .

I'm using vt software v0.5 (released/downloaded on 2015-06-24)

**Comment by atks** [comment]
@trutane - thanks Steve,  vt uses htslib and I think htslib should throw an error in this case.

@pd3 - Petr, should htslib terminate in this case when reading malformed header?

**Comment by pd3** [comment]
Yes, that's a bug, the error is not handled properly. Thanks for reporting!

**Comment by atks** [comment]
@trutane - fixed by htslib, updated in vt.
