### ISSUE TITLE
Incorrect mitochondrial SV normalization

### ISSUE THREAD

**Issue by denisemauldin** [atks/vt#36]
vt normalize produces an incorrect position when transforming a mitochondrial structural variation line:

ORIGINAL FILE:
M    194    .    CT    TC    .    .    NS=1;AN=1;AC=1;CGA_FI=4535|-|ND1|TSS-UPSTREAM|UNKNOWN-INC&4536|-|ND2|TSS-UPSTREAM|UNKNOWN-INC&4549|-|RNR1|TSS-UPSTREAM|UNKNOWN-INC&4558|-|TRNF|TSS-UPSTREAM|UNKNOWN-INC&4565|-|TRNI|TSS-UPSTREAM|UNKNOWN-INC&4567|-|TRNL1|TSS-UPSTREAM|UNKNOWN-INC&4569|-|TRNM|TSS-UPSTREAM|UNKNOWN-INC&4577|-|TRNV|TSS-UPSTREAM|UNKNOWN-INC    GT:PS:FT:GQ:HQ:EHQ:CGA_CEHQ:GL:CGA_CEGL:DP:AD:CGA_RDP    1:.:PASS:9733:9733,.:9733,.:25,.:-9733,0:-25,0:482:482,.:0
M    **196**    GS000012056-ASM_10_L    T    [M:232[CT    .    .    NS=1;SVTYPE=BND;MATEID=GS000012056-ASM_10_R;CGA_BF=0.00    GT:FT:CGA_BNDMPC:CGA_BNDPOS:CGA_BNDDEF:CGA_BNDP    1:MPCBT:3:196:[232[CT:PRECISE

NORMALIZED FILE:
chrM    194    .    CT    TC    .    PASS    NS=1;AN=1;AC=1;CGA_FI=4535|-|ND1|TSS-UPSTREAM|UNKNOWN-INC&4536|-|ND2|TSS-UPSTREAM|UNKNOWN-INC&4549|-|RNR1|TSS-UPSTREAM|UNKNOWN-INC&4558|-|TRNF|TSS-UPSTREAM|UNKNOWN-INC&4565|-|TRNI|TSS-UPSTREAM|UNKNOWN-INC&4567|-|TRNL1|TSS-UPSTREAM|UNKNOWN-INC&4569|-|TRNM|TSS-UPSTREAM|UNKNOWN-INC&4577|-|TRNV|TSS-UPSTREAM|UNKNOWN-INC    GT:GQ:HQ:EHQ    1:9733:9733,.:9733,.
M    **195**    GS000012056-ASM_10_L    T    T[M:232[C    .    .    NS=1;SVTYPE=BND;MATEID=GS000012056-ASM_10_R;CGA_BF=0;OLD_VARIANT=M:196:T/[M:232[CT    GT:FT:CGA_BNDMPC:CGA_BNDPOS:CGA_BNDDEF:CGA_BNDP    1:MPCBT:3:196:[232[CT:PRECISE

C is the reference at position 195.  T is the reference at 196.

**Comment by atks** [comment]
Hi Denise,

May I know which reference file you are using?  According to hs37d5.fa, MT:194-195 is CT.

**Comment by denisemauldin** [comment]
I'm using hg19:

http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chrM%3A194-196&hgsid=443991399_DDfyhpYMm2Jt5LTrTRB9k35Fg2rO

**Comment by atks** [comment]
So there are 3 issues.

1.  I think your original file is based on rCRS NC_012920 version of the mitochondria, which is 16569 bases long compared to the mitochondria reference in HG19 which is 16571 long.  So you should use the appropriate version.

2. The current version of vt normalize should be shouting an error when the REF bases do not match the  reference FASTA file, so  it is weird that it does not.

3. vt is actually ignorant SVs represented in that form and thus it left aligned it 1 base to the left and stopped when it could not go any further.

What does T T[M:232[C mean exactly?

**Comment by denisemauldin** [comment]
The reason why this error is showing up for me is that doing a bcftools merge on this file and another file is showing that this file has an incorrect REF at chrM:195 (C vs T).  

The contig length for chrM in the file is listed as 16569.  

This is the excerpt from the VCF manual about SVTYPE=BND lines:

"An arbitrary rearrangement event can be summarized as a set of novel adjacencies. Each adjacency ties together 2 breakends. The two breakends at either end of a novel adjacency are called mates.
There is one line of VCF (i.e. one record) for each of the two breakends in a novel adjacency. A breakend record is identified with the tag “SYTYPE=BND” in the INFO field. The REF field of a breakend record indicates a base or sequence s of bases beginning at position POS, as in all VCF records. The ALT field of a breakend record indicates a replacement for s. This “breakend replacement” has three parts:
1. The string t that replaces places s. The string t may be an extended version of s if some novel bases are inserted during the formation of the novel adjacency.
2. The position p of the mate breakend, indicated by a string of the form “chr:pos”. This is the location of the first mapped base in the piece being joined at this novel adjacency.
3. The direction that the joined sequence continues in, starting from p. This is indicated by the orientation of square brackets surrounding p.
These 3 elements are combined in 4 possible ways to create the ALT. In each of the 4 cases, the assertion is that s is replaced with t, and then some piece starting at position p is joined to t. The cases are:
REF ALT Meaning
s t[p[ piece extending to the right of p is joined after t
s t]p] reverse comp piece extending left of p is joined after t
s ]p]t piece extending to the left of p is joined before t
s [p[t reverse comp piece extending right of p is joined before t
The example in Figure 1 shows a 3-break operation involving 6 breakends. It exemplifies all possible orientations of breakends in adjacencies. Notice how the ALT field expresses the orientation of the breakends.
#CHROM POS ID REF ALT QUAL FILTER INFO
2 321681 bnd W G G]17:198982] 6 PASS SVTYPE=BND
2 321682 bnd V T ]13:123456]T 6 PASS SVTYPE=BND
13 123456 bnd U C C[2:321682[ 6 PASS SVTYPE=BND
13 123457 bnd X A [17:198983[A 6 PASS SVTYPE=BND
17 198982 bnd Y A A]2:321681] 6 PASS SVTYPE=BND
17 198983 bnd Z C [13:123457[C 6 PASS SVTYPE=BND

Is there a flag to have vt normalize skip SVTYPE=BND events if it doesn't understand them?

Thanks,
Denise

**Comment by atks** [comment]
Thanks for the explanation.  I've just fixed it.  So vt now recognizes break ends and will ignore such SVs.  Please pull and recompile.

To see that it works, use vt peek on the file, and you will see these structural variants summarized as <BND>s under the category SVs.  And of course, please test normalize on it too.

**Comment by atks** [comment]
One more thing to note is that your original file has Mitochondria represented as M, but the error flagged chrM.  So that sometimes give an issue.  Can you double check again using samtools faidx?

>samtools faidx ~/ref/genome/hs37d5.fa MT:194-195
>MT:194-195
CT

**Comment by denisemauldin** [comment]
Hi Adrian,

Yes, I correct the 'chr' format differences when I transform the file, which is why the normalized file has a chr in front (as I'm going to do a bcftools merge with another file that has a chr at the front).

samtools faidx build37.fa chrM:194-196
>chrM:194-196
CTT

Thanks for the quick fix.  I'll test it and let you know how it works. :)

**Comment by atks** [comment]
@denisemauldin - I'm assuming all is fine now, closing this issue, please let me know if it did not work.
