### ISSUE TITLE
Segmentation fault 11 when running vt subset on mac

### ISSUE THREAD

**Issue by jzook** [atks/vt#38]
I've tried running vt subset on a couple different vcf files, and I keep getting a segmentation fault: 11 error.  make test works fine without errors. Any idea what might be happening? Here's the command and error:

PN105860:vt jzook$ ./vt subset -s /Users/jzook/Documents/AJTrio/NCBI_IlluminaHiSeq300X_cortex_09042015/HG002sample.txt -o /Users/jzook/Documents/AJTrio/NCBI_IlluminaHiSeq300X_cortex_09042015/AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015_insgt49vt.vcf -f "DLEN>49" /Users/jzook/Documents/AJTrio/NCBI_IlluminaHiSeq300X_cortex_09042015/AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015.vcf.gz  
subset v0.5

Options:     input VCF File    /Users/jzook/Documents/AJTrio/NCBI_IlluminaHiSeq300X_cortex_09042015/AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015.vcf.gz
         [s] sample file list  1 samples
         [f] filter            DLEN>49

Segmentation fault: 11

Here are my clang and gcc versions:
PN105860:vt jzook$ clang --version
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

PN105860:vt jzook$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

Thanks!
Justin

**Comment by atks** [comment]
Hi @jzook,

Is there anyway I can get hold of your files?

**Comment by jzook** [comment]
Thanks for the quick reply! The 2 files I tried (after sorting) were:
ftp://ftp-trace.ncbi.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_Stanford_HiSeq300x_SpiralGenetics_vcf_06042015/HG002run06variants.vcf.gz

and

ftp://ftp-trace.ncbi.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NCBI_IlluminaHiSeq300X_cortex_09042015/AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015.vcf

**Comment by atks** [comment]
May I also have the sample file?  NCBI_IlluminaHiSeq300X_cortex_09042015/HG002sample.txt

**Comment by jzook** [comment]
Not sure if it'll attach properly to this email but it just has "HG002" in
it in case it doesn't.

On Thu, Oct 29, 2015 at 5:08 PM, Adrian Tan <notifications@github.com>
wrote:

> May I also have the sample file?
> NCBI_IlluminaHiSeq300X_cortex_09042015/HG002sample.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atks/vt/issues/38#issuecomment-152327262>.
>

HG002

**Comment by atks** [comment]
hi justin, @jzook 

Can you try converting the input AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015_insgt49vt.vcf into a vcf.gz file and then index it?

vt view AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015_insgt49vt.vcf -o AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015_insgt49vt.vcf.gz

vt index AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015_insgt49vt.vcf.gz

Then try the subset routine again. Let me know if that works.

The reason for this is that htslib works with BCF as the underlying data structure, so if the headers are not well defined, i.e. lacking the contigs meta header, errors will occur if the program tries to use information from the record.

vt view can still convert the file to vcf.gz because it simply prints out the "read in" string record from the VCF file and then compresses it, thereby circumventing the underlying BCF data structure.

Another way to bypass the missing contig headers is to use the alternate header mechanism described in the following link http://genome.sph.umich.edu/wiki/Vt#Alternate_headers

**Comment by atks** [comment]
@jzook 

I managed to test this on a mac, it gave a similar error, segmentation fault: 11.  even with the indexed gzipped files.

will get back to you on this.

**Comment by jzook** [comment]
Thanks, Adrian! Let me know if you need any more information from me.

**Comment by atks** [comment]
Hi Justin, @jzook 

I think the problem seems to be in the way the compiler handles the macros used in the k*.h template free libraries from ac3 used in htslib.  I tried tracing the errors for several functions and they ultimately break at places where I use khash.h or where htslib functions are called. 

@pd3 - Petr - is htslib fully supported on compilers from mac?



I can't solve this problem without

**Comment by pd3** [comment]
I never had a problem with running htslib and bcftools on mac. Not sure what's going on here.

**Comment by atks** [comment]
Thanks @pd3.  I tried bcftools on mac, and it is working fine on all the tests I had on it.

@jzook - vt still requires that you have a complete header description for functions that output a VCF file for it to run correctly.  To resolve this, you can copy the following header and save it as AJtrio_HiSeq300X_cortex_variants_GRCh37_09042015.vcf.hdr to make use of vt's alternate header reading mechanism.  (http://genome.sph.umich.edu/wiki/Vt#Alternate_headers)  or simply bgzip your input file and tabix it.

The other occurrences of segmentation fault 11 occurs when khash is initialized outside of a block where it is used.

Let me know if this works.  The tests work fine on my mac.

  ##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=21/07/15
##phasing=none, though some calls involve phasing clustered variants
##variants_justified=left
##ALT=<ID=COMPLEX,Description="Complex variant, collection of SNPs and indels">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DEL_INV,Description="Deletion + Inversion">
##ALT=<ID=INDEL,Description="Insertion-deletion">
##ALT=<ID=INS,Description="Insertion of novel sequence">
##ALT=<ID=INS_INV,Description="Insertion + Inversion">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=INV_INDEL,Description="Inversion+indel - this script overcalls these, so worth checking">
##ALT=<ID=PH_SNPS,Description="Phased SNPs">
##ALT=<ID=SNP,Description="SNP">
##ALT=<ID=SNP_FROM_COMPLEX,Description="SNP called from a cluster of phased SNPs or complex SNP/indel , split out for easier comparison with other SNP call sets">
##FILTER=<ID=MAPQ,Description="5prime flank maps to reference with mapping quality below 40">
##FILTER=<ID=MISMAPPED_UNPLACEABLE,Description="Stampy mapped the variant (using the 5p-flank) confidently (mapqual> 40) to a place where the ref-allele does not match">
##FILTER=<ID=MULTIALLELIC,Description="Cortex does not call multiallelic sites, but combining run_calls VCFs can produce them. Filtered as current genotyper assumes biallelic.">
##FILTER=<ID=OVERLAPPING_SITE,Description="If Stampy (or combining VCFs) has placed two biallelic variants overlapping, they are filtered">
##FORMAT=<ID=COV,Number=2,Type=Integer,Description="Number of reads on ref and alt alleles">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GT_CONF,Number=1,Type=Float,Description="Genotype confidence. Difference in log likelihood of most likely and next most likely genotype">
##FORMAT=<ID=SITE_CONF,Number=1,Type=Float,Description="Probabilitic site classification confidence. Difference in log likelihood of most likely and next most likely model (models are variant, repeat and error)">
##INFO=<ID=PV,Number=1,Type=Integer,Description="Possible variation in clean indel position">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of variant">
##contig=<ID=1>
##contig=<ID=10>
##contig=<ID=11>
##contig=<ID=12>
##contig=<ID=13>
##contig=<ID=14>
##contig=<ID=15>
##contig=<ID=16>
##contig=<ID=17>
##contig=<ID=18>
##contig=<ID=19>
##contig=<ID=2>
##contig=<ID=20>
##contig=<ID=21>
##contig=<ID=22>
##contig=<ID=3>
##contig=<ID=4>
##contig=<ID=5>
##contig=<ID=6>
##contig=<ID=7>
##contig=<ID=8>
##contig=<ID=9>
##contig=<ID=X>
##contig=<ID=Y>
##INFO=<ID=VT_AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=VT_AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG002	HG003	HG004

**Comment by atks** [comment]
@jzook  - I missed the -f "DLEN>49" option in your original case.  The error came about because I changed the way the filter was used but did not update subset.cpp accordingly.  It should work now.

**Comment by jzook** [comment]
It's working well now.  Thanks!
