### ISSUE TITLE
CGI bz2 file throws Not a VCF/BCF file

### ISSUE THREAD

**Issue by denisemauldin** [atks/vt#39]
Hi,

I have a bunch of Complete Genomics VCF files that I want to normalize.  They're compressed with bzip2 and they have the following header start:

##fileformat=VCFv4.1
##fileDate=20140715
##center=Complete Genomics
##source=CGAPipeline_2.0.2.26;cgatools_1.8.0
##source_GENOME_REFERENCE=NCBI build 37
##source_GENE_ANNOTATIONS=NCBI build 37.2
##source_DBSNP_BUILD=dbSNP build 132
##source_COSMIC=COSMIC v48
##source_DGV_VERSION=9
##source_MIRBASE_VERSION=miRBase version 16
##source_PFAM_DATE=April 21, 2011
##source_REPMASK_GENERATED_AT=2011-Feb-15 10:08
##source_SEGDUP_GENERATED_AT=2010-Dec-01 13:40
##phasing=partial
##source_MAX_PLOIDY=10
##source_NUMBER_LEVELS=GS01489-DNA_A06:5
##source_NONDIPLOID_WINDOW_WIDTH=100000
##source_MEAN_GC_CORRECTED_CVG=GS01489-DNA_A06:55.52
##source_MEI_1000G_ANNOTATIONS=INITIAL-DATA-RELEASE

Right now vt normalize throws:
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file

vt normalize vcfBeta-ASM.vcf.bz2 -o normVcf.out -r hg19_CGI.fa.bz2

Please update to allow these files to be normalized.

Thanks,
Denise

**Comment by atks** [comment]
Hi Denise,

The i/o library that vt uses - htslib only recognizes bgzipped files.  bz2 is a different compression standard.

A work around is to simply unzip the file and stream it to vt.

e.g  bunzip2 file.bz2 | vt normalize - -r ref.fa -o out.bcf

**Comment by denisemauldin** [comment]
Ok.  Will do.  Thanks.
