### ISSUE TITLE
make error (Mac)

### ISSUE THREAD

**Issue by mdozmorov** [atks/vt#40]
On Mac OS X 10.9.5, `make` generates error:

----

g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o paste_and_compute_features_sequential.o -c paste_and_compute_features_sequential.cpp
paste_and_compute_features_sequential.cpp:699:9: error: use of undeclared identifier 'isnanf'; did you mean 'isnan'?
          if ( isnanf(fic) ) fic = 0;
               ^~~~~~
               isnan
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:425:1: note: 'isnan' declared here
isnan(_A1 __x) _NOEXCEPT
^
1 error generated.
make: *** [paste_and_compute_features_sequential.o] Error 1

----

Shouldn't 
https://github.com/atks/vt/blob/master/paste_and_compute_features_sequential.cpp#L699
be `if ( isnan(fic) ) fic = 0;`?

**Comment by atks** [comment]
isnanf() is a unix standard but not posix, that's why it is not recognized in OSX.

I've made a workaround. 
isnanf(fic) => isnan((double)fic)

I've checked it and it works. It seems that without casting the float to double works too in Linux and OSX but I will just keep the double cast just in case since the 2 functions are stipulated specifically for different types in Unix.
 
You can pull it and compile it now in Mac.

**Comment by mdozmorov** [comment]
Works great, thanks for quick response!

**Comment by mobcdsw2** [comment]
Hi,
I'm getting a similar error on osx:

g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o paste_and_compute_features_sequential.o -c paste_and_compute_features_sequential.cpp
paste_and_compute_features_sequential.cpp: In member function ‘void {anonymous}::Igor::paste_and_compute_features_sequential()’:
paste_and_compute_features_sequential.cpp:699:26: error: ‘isnan’ was not declared in this scope
    if ( isnan((double)fic) ) fic = 0;   
                          ^

Any ideas?

Thanks

**Comment by atks** [comment]
I just tried compiling on OSX v10.10.5 and had no issues.

Can you try pulling the latest version and recompiling?

Just type git pull.  Or do a fresh clone.

**Comment by mobcdsw2** [comment]
Thanks for the quick reply.

I've tried a fresh clone on this machine (OSX v.10.11.3) and get the same issue BUT when I tried a separate machine running OSX v10.11.2 it works fine.  Probably something funny with my setup on the original machine.  If I can work it out I'll let you know but at least I've got a working version somewhere! 
 
Thanks

**Comment by atks** [comment]
ok, do let me know if you figure out what happened and if there is a fix for it. thanks!
