### ISSUE TITLE
decompose_blocksub should optionally output phased genotypes and PS tags for decomposed MNPs

### ISSUE THREAD

**Issue by andyrimmer** [atks/vt#41]
Breaking up MNPs and other complex variants loses information about which variants occur on the same haplotype. To avoid this, decompose_blocksub could output phased genotypes (i.e. | instead of /) and PS tags in the per-sample data

**Comment by atks** [comment]
ok thanks. I've read it, I now understand what you are doing. It sounds
straightforward for input phased data.

**Comment by andyrimmer** [comment]
Yes, it should be straightforward. I'm working on this now.

**Comment by atks** [comment]
implemented by Andy, pull request merged.
