### ISSUE TITLE
make error (Mac 10.11.3)

### ISSUE THREAD

**Issue by davemcg** [atks/vt#43]
$ make test
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o profile_mendelian.o -c profile_mendelian.cpp
profile_mendelian.cpp:45:5: error: unknown type name 'float_t'; did you mean 'float'?
    float_t min_gq;
    ^~~~~~~
    float
profile_mendelian.cpp:463:16: error: use of undeclared identifier 'NAN'
        return NAN;
               ^
profile_mendelian.cpp:518:26: error: use of undeclared identifier 'NAN'
        return (het==0 ? NAN : hom/het);
                         ^
profile_mendelian.cpp:573:32: error: use of undeclared identifier 'NAN'
        return ((het+hom)==0 ? NAN : het/(hom+het)*100);
                               ^
4 errors generated.
make: *** [profile_mendelian.o] Error 1

**Comment by atks** [comment]
sorry about that, please pull and recompile again.

**Comment by davemcg** [comment]
Yep, works. Thanks!
