### ISSUE TITLE
build error with gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

### ISSUE THREAD

**Issue by hmkim** [atks/vt#44]
My system have..
- gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
- Ubuntu 12.04.5 LTS \n \l

$ git clone https://github.com/atks/vt.git
$ cd vt
$ make
...
make[1]: Leaving directory `/BiO/BioTools/vt/lib/libsvm'
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o align.o -c align.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o allele.o -c allele.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_1000g.o -c annotate_1000g.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_dbsnp_rsid.o -c annotate_dbsnp_rsid.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_indels.o -c annotate_indels.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_mendelian.o -c annotate_mendelian.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_regions.o -c annotate_regions.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_variants.o -c annotate_variants.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o annotate_vntrs.o -c annotate_vntrs.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o augmented_bam_record.o -c augmented_bam_record.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bam_ordered_reader.o -c bam_ordered_reader.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bcf_genotyping_buffered_reader.o -c bcf_genotyping_buffered_reader.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bcf_ordered_reader.o -c bcf_ordered_reader.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bcf_ordered_writer.o -c bcf_ordered_writer.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bcf_synced_reader.o -c bcf_synced_reader.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o bed.o -c bed.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o candidate_motif_picker.o -c candidate_motif_picker.cpp
candidate_motif_picker.cpp: In member function ‘bool CandidateMotifPicker::get_indel(std::string, std::string, std::string&)’:
candidate_motif_picker.cpp:186:13: error: ‘std::string’ has no member named ‘pop_back’
candidate_motif_picker.cpp:187:13: error: ‘std::string’ has no member named ‘pop_back’
make: *** [candidate_motif_picker.o] Error 1

I checked this thread. (http://stackoverflow.com/questions/20891441/using-string-pop-back-and-string-back)

Could I build vt with my system?

**Comment by atks** [comment]
I've changed the pop_back call to 
ref.erase(ref.size()-1, 1);
alt.erase(alt.size()-1, 1);

This should work.

**Comment by hmkim** [comment]
Ok. I solve this issue with your update version.

Thank you very much!
