### ISSUE TITLE
Reference mismatch, 'c' isnt' a 'C'

### ISSUE THREAD

**Issue by isbslagelwa** [atks/vt#46]
Similar to issue #45 we're also getting the following error:

```
[variant_manip.cpp:96 is_not_ref_consistent] reference bases not consistent: chrX:60000-60000  c(REF) vs C(FASTA)
[normalize.cpp:209 normalize] Normalization not performed due to inconsistent reference sequences. (use -n or -m option to relax this)
```

and incidentally we are using both the -n and the -m options.

**Comment by atks** [comment]
please pull and give it a try.  I've made the code case insensitive for that function.

**Comment by isbslagelwa** [comment]
Works.  Thanks!

**Comment by richardwfrancis** [comment]
I realise this is an old, closed issue but I've just run in to the converse of this where the FASTA is lower case. As the REF is consistently being switched `toupper()` I get the same message as above for identical sequence just in the opposite case. Is it safe to `toupper()` both the REF and FASTA in the string comparison within this function?

**Comment by lbeltrame** [comment]
I did something of the sort myself:

```diff
diff --git a/variant_manip.cpp b/variant_manip.cpp
index f512895..ad201d7 100644
--- a/variant_manip.cpp
+++ b/variant_manip.cpp
@@ -77,9 +77,9 @@ int32_t VariantManip::is_not_ref_consistent(bcf_hdr_t *h, bcf1_t *v)
     int32_t is_not_consistent = 0;
     for (uint32_t i=0; i<ref_len; ++i)
     {
-        if (toupper(vcf_ref[i]) != ref[i])
+        if (toupper(vcf_ref[i]) != toupper(ref[i]))
         {
-            if (ref[i]=='N' || toupper(vcf_ref[i])=='N')
+            if (toupper(ref[i])=='N' || toupper(vcf_ref[i])=='N')
             {
                 is_not_consistent = 1;
             }
```

Seems to work, although I can't vouch for every case, but at least for me it was just a matter of casing.

**Comment by travc** [comment]
I'm hitting the same issue as @richardwfrancis 
@atks Could we get this reopened and the fix @lbeltrame proposed adopted?

**Comment by richardwfrancis** [comment]
Hi @travc.
Take a look at the -n and -m options and see which one works for your scenario. I found -n was perfect for my needs and solved my issue above.
Cheers

**Comment by travc** [comment]
@richardwfrancis Thanks for the suggestion, though neither `-n` or `-m` solves the problem for me.  Honestly seems like a bug, because you'd think they should.

I ended up having to use @lbeltrame's patch.

**Comment by NTNguyen13** [comment]
> I did something of the sort myself:
> 
> ```diff
> diff --git a/variant_manip.cpp b/variant_manip.cpp
> index f512895..ad201d7 100644
> --- a/variant_manip.cpp
> +++ b/variant_manip.cpp
> @@ -77,9 +77,9 @@ int32_t VariantManip::is_not_ref_consistent(bcf_hdr_t *h, bcf1_t *v)
>      int32_t is_not_consistent = 0;
>      for (uint32_t i=0; i<ref_len; ++i)
>      {
> -        if (toupper(vcf_ref[i]) != ref[i])
> +        if (toupper(vcf_ref[i]) != toupper(ref[i]))
>          {
> -            if (ref[i]=='N' || toupper(vcf_ref[i])=='N')
> +            if (toupper(ref[i])=='N' || toupper(vcf_ref[i])=='N')
>              {
>                  is_not_consistent = 1;
>              }
> ```
> 
> Seems to work, although I can't vouch for every case, but at least for me it was just a matter of casing.

I edited the variant_manip.cpp file but the error still happen :(

**Comment by tomSimonet** [comment]
Hi
same problem, with 0.57721 release:
error raised with vcf upper case and fasta lower case.

```
./vt/vt normalize -n -r db/hg19.fa smpl1_tmp.vcf -o smpl1_norm.vcf
[variant_manip.cpp:96 is_not_ref_consistent] reference bases not consistent: chr5:1295222-1295227  CCGGAG(REF) vs ccggag(FASTA)
[normalize.cpp:214 normalize] Normalization skipped due to inconsistent reference sequences

cat smpl1_norm.vcf | grep -P '^chr5\t129522.\t' | cut -f1-5
chr5	1295223	.	CCGGAG	CCGGAA
```

but NOT with 0.5772 release (even without the -n parameter)

```
./vt_v0.5772/vt normalize -r db/hg19.fa smpl1_tmp.vcf -o smpl1_norm.vcf

cat smpl1_norm.vcf | grep -P '^chr5\t129522.\t' | cut -f1-5
chr5	1295228	.	G	A
```


regarding the files variant_manip.cpp :

```
diff vt/variant_manip.cpp vt_v0.5772/variant_manip.cpp 
69c69
<     char *ref = faidx_fetch_seq(fai, chrom, pos0, pos0+rlen-1, &ref_len);
---
>     char *ref = faidx_fetch_uc_seq(fai, chrom, pos0, pos0+rlen-1, &ref_len);
```

if this may help...
meanwhile, I have to stay on previous release
many thanks
