### ISSUE TITLE
v0.557 still reporting version as v0.5

### ISSUE THREAD

**Issue by tseemann** [atks/vt#47]
Using this source https://github.com/atks/vt/archive/0.577.tar.gz

```
% vt view
...
view v0.5
```

I was expecting to see `view v0.557` ?

**Comment by atks** [comment]
I'm keeping the subversions of each program different from the overall version of vt.   But to be honest, I haven't really been updating the individual versions either.

**Comment by tseemann** [comment]
Would you consider a global `--version` option?

(So pipelines can query/record the version used)

**Comment by atks** [comment]
ok, done.  vt --version will yield:
vt v0.5772-9e2e0697
The MIT license
Copyright (c) 2013 Adrian Tan <atks@umich.edu>
