### ISSUE TITLE
Typo leads to failed compile

### ISSUE THREAD

**Issue by davidhanna** [atks/vt#48]
paste_genotypes.cpp:729:9: error: use of undeclared identifier 'isnanf'; did you mean 'isnan'?
          if ( isnanf(fic) ) fic = 0;     
               ^~~~~~
               isnan

Changing to isnan allows successful compilation

**Comment by atks** [comment]
thanks, it's a throwback from https://github.com/atks/vt/issues/40
where isnanf() is not POSIX compliant and is not recognized by MAC compilers.
fixed.

**Comment by deannachurch** [comment]
I just ran into this- will it be fixed soon?

**Comment by atks** [comment]
can you please pull and try.

**Comment by deannachurch** [comment]
That worked- thanks!
