### ISSUE TITLE
REF prefixes differ after vt normalizing two files

### ISSUE THREAD

**Issue by evalanguaria** [atks/vt#5]
Hello,
I have vt normalized two vcf files and when I try to merge them I get REF prefixes differ error in multiple positions. Here are the positions, REF and ALT before and after vt normalization. I couldn't understand how vt normalizing can result in different REF alleles at the same positions. Thank you for your help

file1 before vt normalization:                
35301		TTAAAAAAACTTATAAACGTAAA	TCAAAAAAAACTTATAAACGTAAG
file1 after normalization:
35301		T	TC
file2 after normalization
35301		A	AT		OLD_VARIANT=gi|602625715|gb|AE004092.2|:35302:T/TT

**Comment by atks** [comment]
Hi Eva,  are you using the same reference file for both?   Can you link me to it?

**Comment by atks** [comment]
also, are you the same Eva raising the vt decompose issue on GATK's forum?

**Comment by evalanguaria** [comment]
hi atks,
yes I am the same Eva and yes I am using the same reference file with NCBI accession AE004092

**Comment by atks** [comment]
Can you link me to both your files and your FASTA file too?  It will be easier fix the problem if I can recreate it on my side.

**Comment by evalanguaria** [comment]
you can find the 2 vcfs and the fasta here https://github.com/evalanguaria/vt

**Comment by atks** [comment]
Hi Eva,  Can you change the sequence name in the fasta file from >gi|602625715|gb|AE004092|  to >gi|602625715|gb|AE004092.2|?    Delete the .fai file and rerun vt normalize.

The difference in sequence name caused the problem, because your VCF file does not have contig headers, vt normalize does not check for consistency,  I'll add some code to warn if the contig cannot be found in the reference fasta file index.

**Comment by atks** [comment]
Can you also send me the example that caused vt decompose to have a segmentation fault?

**Comment by atks** [comment]
Also, are you using a recent version of vt?  That difference in sequence name should have thrown an error in the first place because htslib's reference base API would also have thrown an error.  My current version reflects that too.

**Comment by evalanguaria** [comment]
Thank you atks for the immediate reply. I will change the sequence name as you suggested and let you know how it goes. I am using a recent version of vt, I pulled an update today. Here is a link to the vcf file that caused the segmentation fault (sorry I couldn't push to my git repo) https://www.dropbox.com/s/lvp0l5sgmfff4xi/segmentation_fault.vcf?dl=0

**Comment by atks** [comment]
Thanks Eva,  just to double check, is the GT value for your records correct?  It has 50 copies of a chromosome? 

gi|602625715|gb|AE004092.2|     981     .       C       T       38302.3 .       AB=0.0677458;ABP=28678.1;AC=3;AF=0.06;AN=50;AO=1197        GT:DP:RO:QR:AO:QA       0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/1/1/1:17669:16453:607597:1197:42792

**Comment by atks** [comment]
For decompose,  when you run it, htslib warns that
"[W::vcf_parse] contig 'gi|602625715|gb|AE004092.2|' is not defined in the header. (Quick workaround: index the file with tabix.)"

So you can bgzip the vcf and tabix it to get decompose to work.

Alternatively, you can add the header ##contig=<ID=gi|602625715|gb|AE004092.2|,length=1852433>, and all will be fine.

I have updated decompose to handle any number of ploidy, so the reported genotypes will be fine still.

**Comment by evalanguaria** [comment]
yes atks the ploidy is right. i will do all that you suggested and let you know of the result. thank you again.

**Comment by atks** [comment]
great.  May you close your comments on GATK forum too?

**Comment by evalanguaria** [comment]
Hi atks. I did what you suggested and changed the chromosome name on my vcf files to gi|602625715|gb|AE004092| to be the same as that in the fasta file and bgziped and tabix indexed the vcf files and decompose is working fine. However when I am trying to apply vt normalize, I am getting this error "[variant_manip.cpp:543 right_trim_or_left_extend] failure to extract base from fasta file: gi|602625715|gb|AE004092|:144: >". Can you tell me why this might be? Thank you

**Comment by evalanguaria** [comment]
Hi atks. Everything is working fine now. thank you for all your help

**Comment by atks** [comment]
Hi Eva,

We've just published the paper on the normalization algorithm, just fyi if
someone asks about the validity of the algorithm.

http://bioinformatics.oxfordjournals.org/content/early/2015/02/19/bioinformatics.btv112.abstract?keytype=ref&ijkey=2kB1TkBGzkoP1gd




warm regards,

Adrian

**Comment by evalanguaria** [comment]
Hi Adrian,

Congrats on the paper and thank you for the link ; I appreciate it.
Regarding, testing vt decompose on data with ploidy > 2, I didn't notice
you sent me a new message; sorry about that. I did use vt decompose on such
data and didn't give me any errors but at the time I didn't check if the
results make sense. If I find anything, I will let you know.

Best,
Eva
