### ISSUE TITLE
decompose 

### ISSUE THREAD

**Issue by dwaggott** [atks/vt#50]
Hello,

Question. After a decompose should certain INFO tags be changed to reflect the one line, one ALT output? i.e. `Number=A --> Number=1` ? I got an error with a tool expecting it. 

`##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele">`

**Comment by atks** [comment]
Hi,

number=A means that the number of values expected is the number of alternate alleles.  so when decompose splits up all the multiallelics into biallelics, the number of alternative alleles is 1 so all is fine.

see section 1.4.2 in https://samtools.github.io/hts-specs/VCFv4.3.pdf

a way to get around this for your problem, is to pipe the VCF into a script that changes it to number=1 and then pipe it into the tool you were referring to.
