### ISSUE TITLE
Multiple operations?

### ISSUE THREAD

**Issue by slagelwa** [atks/vt#53]
I'd love to do a filter + normalization at the same time.  We're filtering on variants and piping this back into vt normalize.   Be so much better if we could filter and normalize at the same time in the same process to reduce memory and I/O.

**Comment by atks** [comment]
Right now, vt is generally modeled in the fashion of unix programs in which each function only does one thing but does it well.  I prefer to leave it as such.  the memory and i/o should be minimal.  When you pipe the output, do you use "-o +"?  This ensures that the output is not compressed and it saves alot of time.   http://genome.sph.umich.edu/wiki/Vt#Uncompressed_BCF_streams

**Comment by slagelwa** [comment]
Currently not specifying the output with -o, simply piping STDOUT back into another vt process.

**Comment by atks** [comment]
try using with "-o +", the computational time in compressing and decompressing BCF files is significant.

**Comment by slagelwa** [comment]
Thanks, just saw that in your documentation and tried it.  I didn't get as a substantial performance improvement as you suggested but then again my test data set is pretty small.  I'll try it in a real world scenario.  However I did notice something that significantly affected the performance of the normalization -- whether or not the fasta database is compressed.  Uncompressed on my rather small test set it takes ~35s.  If its block gzipped, it takes > 5 mins.

**Comment by atks** [comment]
Compression and decompression in general are computationally expensive. 
http://genome.sph.umich.edu/wiki/Vt#BCF_Compression_Levels_vs_Compression_Time
