### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by saumyajamuar** [atks/vt#55]
Hi,

I am trying to install vt using the commands stated in the wiki at http://genome.sph.umich.edu/wiki/Vt#Installation

However, I am receiving a fatal error..

>
> In file included from annotate_indels.cpp:24:
> In file included from ./annotate_indels.h:28:
> In file included from ./vntr_annotator.h:28:
> In file included from ./candidate_motif_picker.h:31:
> In file included from ./motif_tree.h:28:
> ./motif_map.h:27:10: fatal error: 'cstdint' file not found
> #include <cstdint>
>          ^
> 1 error generated.
> make: *** [annotate_indels.o] Error 1

Would appreciate any guidance.

Regards,
Saumya

**Comment by atks** [comment]
It seems like you are running it on a mac.   May I ask that you update Xcode to the latest version and try compiling again.

My version of g++ on a mac where vt compiles has the following version information.
adriantks@pscalare:~ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by saumyajamuar** [comment]
Thanks. Will do.

Regards,
Saumya
