### ISSUE TITLE
Don't understand behavior of decomposition

### ISSUE THREAD

**Issue by martiliasf** [atks/vt#56]
I have to decompose a VCF and used the instructions provided for Gemini described here: 
http://gemini.readthedocs.io/en/latest/

```
zless $VCF \
   | sed 's/ID=AD,Number=./ID=AD,Number=R/' \
   | vt decompose -s - \
   | vt normalize -r $REF - \
```
However, when I dug back into some multiallelic sites I came across this:

Original VCF - 

```1       4992134 rs35519208      TTATATA T,TTATATATATATATA```

decomposed vcf
```1       4992134 rs35519208      TTATATA T ```
```1       4992134 rs35519208      T       TTATATATA```

**Comment by atks** [comment]
Hi @martiliasf,

The progression is as follows:

A. initial variant
1 4992134 rs35519208 TTATATA T,TTATATATATATATA

B. split into biallelics (done by vt decompose)
1 4992134 rs35519208 TTATATA T
1 4992134 rs35519208 TTATATA TTATATATATATATA

C. trim extraneous nucleotides for parsimony and left align. (done by normalize)
1 4992134 rs35519208 TTATATA T
1 4992134 rs35519208 T TTATATATA

**Comment by martiliasf** [comment]
Awesome. Thank you so much for the explanation and your patience with a NGS noob.
