### ISSUE TITLE
Incorrect normalization?

### ISSUE THREAD

**Issue by FrankFeng** [atks/vt#58]
The original variant is:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	83826	rs58857344	AAAGA	A,AAA	.	.	.
```
The first ALT allele is `AAGA` deleted, and the second is `GA` deleted.

After I ran `vt normalize original_variant.vcf -r $b37`, the normalized variant is:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	83825	rs58857344	GAAAG	G,GAA	.	.	OLD_VARIANT=1:83826:AAAGA/A/AAA
```
Now the first ALT allele is `AAAG` deleted, and the second is `AG` deleted.

It seems that is incorrect.

VT version: vt v0.5772-60f436c3

**Comment by FrankFeng** [comment]
I just tried bcftools, and it gave me the same left-aligned result as VT did. The version of bcftools is bcftools_normVersion=1.3.1-148-ge6fb7f2+htslib-1.3.2-129-gdaae2ea

I really don't understand. Can you please help?

**Comment by FrankFeng** [comment]
I just figured it out that both VT and BCFTOOLS did the correct left-alignment. I didn't consider the context of the reference genome, so I was wrong. I am closing this issue. Thanks!

**Comment by atks** [comment]
no problem.  bcftools uses the same normalization algorithm as vt.
