### ISSUE TITLE
Segmentation fault on Decompose

### ISSUE THREAD

**Issue by Vaidhy-M** [atks/vt#59]
Hi, I am running VT Decompose on a multi-sample vcf file generated by GATK  as part of the preprocess workflow to load the file onto GEMINI browser and it terminates with Segmentation Fault. When I reran the command after updating VT it again failed but this time with an output file of bigger size. The command I used is as follows, 

> vt decompose -s -o output.vcf input.vcf

Kindly clarify.

**Comment by atks** [comment]
can you share input.vcf with me?

**Comment by Vaidhy-M** [comment]
The input.vcf is a 285 GB file.

**Comment by atks** [comment]
Can you isolate the record that causes the segmentation fault?

**Comment by atks** [comment]
Hi Vaidhy,

I don't know how to help if I cannot replicate the error on my side.

**Comment by pankajxyz** [comment]
I also encountered this error. It's quite hard to debug to find the root cause of error. By replacing all info column with "." it runs fine. However, I am not able to pinpoint the origin of error.

**Comment by svsuresh** [comment]
**what works**: $ vt view test.vcf; $vt view test.vcf
**What doesn't work**: $ vt decompose test.vcf
**Error**: Segmentation fault
**Output**:
decompose v0.5


options:     input VCF file        test.vcf
         [s] smart decomposition   false (experimental)
         [o] output VCF file       -

##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=VC,Number=1,Type=String,Description="Variation Class">
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=.,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##INFO=<ID=refseq.name,Number=1,Type=String,Description="RefSeq name">
##INFO=<ID=refseq.positionType,Number=1,Type=String,Description="RefSeq genome type position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
Segmentation fault


input:
$ cat test.vcf
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=249250621,assembly=b37>
##contig=<ID=2,length=243199373,assembly=b37>
##contig=<ID=3,length=198022430,assembly=b37>
##contig=<ID=4,length=191154276,assembly=b37>
##contig=<ID=5,length=180915260,assembly=b37>
##contig=<ID=6,length=171115067,assembly=b37>
##contig=<ID=7,length=159138663,assembly=b37>
##contig=<ID=8,length=146364022,assembly=b37>
##contig=<ID=9,length=141213431,assembly=b37>
##contig=<ID=10,length=135534747,assembly=b37>
##contig=<ID=11,length=135006516,assembly=b37>
##contig=<ID=12,length=133851895,assembly=b37>
##contig=<ID=13,length=115169878,assembly=b37>
##contig=<ID=14,length=107349540,assembly=b37>
##contig=<ID=15,length=102531392,assembly=b37>
##contig=<ID=16,length=90354753,assembly=b37>
##contig=<ID=17,length=81195210,assembly=b37>
##contig=<ID=18,length=78077248,assembly=b37>
##contig=<ID=19,length=59128983,assembly=b37>
##contig=<ID=20,length=63025520,assembly=b37>
##contig=<ID=21,length=48129895,assembly=b37>
##contig=<ID=22,length=51304566,assembly=b37>
##contig=<ID=X,length=155270560,assembly=b37>
##contig=<ID=Y,length=59373566,assembly=b37>
##contig=<ID=MT,length=16569,assembly=b37>
##INFO=<ID=VC,Number=1,Type=String,Description="Variation Class">
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=.,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##INFO=<ID=refseq.name,Number=1,Type=String,Description="RefSeq name">
##INFO=<ID=refseq.positionType,Number=1,Type=String,Description="RefSeq genome type position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
2	21232803	.	TG	CA,CG
20	763837	.	CA	TG

**Comment by atks** [comment]
@svsuresh

Hi Suresh,  your VCF file is malformed. Your QUAL, FILTER and INFO fields need explicit missing values as follows.

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
2	21232803	.	TG	CA,CG	.	.	.
20	763837	.	CA	TG	.	.	.
