### ISSUE TITLE
Update htslib to avoid dependency on gcc 4.5 or better

### ISSUE THREAD

**Issue by chapmanb** [atks/vt#7]
Adrian;
Apologies, one more report this morning. The htslib currently in vt has a dependency on gcc 4.5 or better. This got fixed yesterday in devel so it'll be compatible with older versions:

https://github.com/samtools/bcftools/issues/201#issuecomment-73511968

Would it be possible to update htslib in vt to pull in this fix? Thanks much.

**Comment by atks** [comment]
done.
