### ISSUE TITLE
Make issue - fatal error 'lzma.h' file not found

### ISSUE THREAD

**Issue by ehitchcock** [atks/vt#70]
I continue to get a fatal error when following the install instructions for vt..
I am using a mac and have made sure xcode is updated to the most recent version.

I have also confirmed that lzma.h is on my mac. 

$ sudo find /usr -name lzma.h -print
/usr/local/include/lzma.h

used brew install xz and then tried to reinstall vt and still got the fatal error. 

Any guidance/help you have for me would be much appreciated!
Thanks

Full make output is:
cd lib/htslib; /Applications/Xcode.app/Contents/Developer/usr/bin/make libhts.a || exit 1; 
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
gcc -g -Wall -O2 -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.4"' > version.h
gcc -g -Wall -O2 -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [lib/htslib/libhts.a] Error 1

**Comment by atks** [comment]
@ehitchcock 

Can you try updating the xz package on mac using homebrew?  The issue is described in the following link.  https://discussions.apple.com/thread/7895857?start=0&tstart=0

**Comment by atks** [comment]
@ehitchcock 

Can you see if this link helps?  https://github.com/samtools/htslib/issues/493

I tried installing on my mac but I was unable to reproduce the error you experienced.

**Comment by ehitchcock** [comment]
@atks Thanks for you help! I realized I could install vt using hombrew and that was successful! 
brew install homebrew/science/vt
