### ISSUE TITLE
issue with compile

### ISSUE THREAD

**Issue by rebzzy** [atks/vt#71]
Hi - I'm getting the following errors:

g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o interval_tree.o -c interval_tree.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o interval.o -c interval.cpp
g++ -pipe -std=c++0x -O3 -I./lib -I. -I./lib/htslib -I./lib/Rmath -I./lib/pcre2 -D__STDC_LIMIT_MACROS -o lfhmm.o -c lfhmm.cpp
lfhmm.cpp: In member function ‘void LFHMM::collect_statistics(int32_t, int32_t, int32_t)’:
lfhmm.cpp:761: warning: overflow in implicit constant conversion
lfhmm.cpp: In member function ‘void LFHMM::clear_statistics()’:
lfhmm.cpp:868: warning: overflow in implicit constant conversion
lfhmm.cpp:869: warning: overflow in implicit constant conversion
lfhmm.cpp:870: warning: overflow in implicit constant conversion
lfhmm.cpp:871: warning: overflow in implicit constant conversion
lfhmm.cpp:872: warning: overflow in implicit constant conversion
lfhmm.cpp:873: warning: overflow in implicit constant conversion
lfhmm.cpp:874: warning: overflow in implicit constant conversion
lfhmm.cpp:875: warning: overflow in implicit constant conversion
lfhmm.cpp:876: warning: overflow in implicit constant conversion
lfhmm.cpp:877: warning: overflow in implicit constant conversion
lfhmm.cpp:878: warning: overflow in implicit constant conversion
lfhmm.cpp:879: warning: overflow in implicit constant conversion
lfhmm.cpp:881: warning: overflow in implicit constant conversion
lfhmm.cpp:882: warning: overflow in implicit constant conversion
lfhmm.cpp:883: warning: overflow in implicit constant conversion
lfhmm.cpp:884: warning: overflow in implicit constant conversion
...
ector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&)’:
svm_train.cpp:165: error: no matching function for call to ‘sort(__gnu_cxx::__normal_iterator<float**, std::vector<float*, std::allocator<float*> > >, __gnu_cxx::__normal_iterator<float**, std::vector<float*, std::allocator<float*> > >, <unnamed>::Igor::inverse_normalize(std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&)::<anonymous struct>&)’

**Comment by atks** [comment]
@rebzzy  - you need to use a newer version of gcc, at least 4.8.1 and above.

**Comment by rebzzy** [comment]
Thanks!
