### ISSUE TITLE
VCF is truncated if input not sorted

### ISSUE THREAD

**Issue by tdelhomme** [atks/vt#79]
Hi, 

If my input VCF is not sorted, I get an output VCF which is truncated at the last line, and I get this message:

```
[E:bcf_synced_reader.cpp:588 fill_buffer] VCF file not in order: -
```

Is this an expected behaviour?

Thanks!

**Comment by atks** [comment]
It depends on what command you are using.  Based on the error message, you were probably using a command that requires the file to be in order possibly for annotation against a reference VCF file or for comparison with other VCF file.

**Comment by tdelhomme** [comment]
Thanks for your answer! actually the command is `vt uniq`, is this concordant?

**Comment by atks** [comment]
That is expected.  vt uniq assumes the file is ordered, because it is ordered, checking of duplicates is trivial.  I've updated the documentation to mention that. https://genome.sph.umich.edu/wiki/Vt#Drop_duplicate_variants

**Comment by tdelhomme** [comment]
exact! thanks for the doc, will close the issue. :+1:
