### ISSUE TITLE
Vt norm Failed to open fasta file

### ISSUE THREAD

**Issue by WesDe** [atks/vt#81]
Hello,

I am trying to use vt norm in order to normalize vcf file produced by GATKHC and Platypus. I use a reference fasta file home made because i aim to analyze exonic region : I replace intronic region by 'N' world to keep the positions of nucleotides. I am working on Human genome Hg38, my reference file contains each chromosome from 1 to Y.
The home made reference has been used as input for GATKHC and Platypus variant calling without problem. 
However when i run vt normalization an error appears :

> [E::fai_load3] Failed to open FASTA file #MyRefFastaFile
> [variant_manip.cpp:38 VariantManip] Cannot load genome index: #MyRefFastaFile

I removed the .fai, run vt again : the same errors appeared
I removed the .fai, run samtools faidx to make an new .fai, then run vt : the same errors appeared.

I am new with vcf and vcf normalization i may do it wrong, have you any suggestion to fix my problem ? 

Kinds regards,

**Comment by atks** [comment]
@WesDe 

There's something wrong with your FASTA file.  Is there any way you can create a smaller version of your home made FASTA file and reproduce the error and give me access to that FASTA file?

**Comment by WesDe** [comment]
@atks 
You were right, i ran vt using a sample of my reference (chr1 to 12) it worked and broke because i didn't provide chromosome 13 or higher. However, i get the previous error "Failed to open FASTA file #MyRefFastaFile" with a reference file containing chr1 to 13.

Then I sampled my vcf from chr 13 to Y and ran using a reference containing chr 13 to Y and it worked !  So it seems that i have to sample my reference and my vcf in half to avoid the error.

**Comment by atks** [comment]
@WesDe 

You should be able to do it all in one fasta file, if there is a missing chromosome, vt would report that.  There's probably something wrong with your fasta file.
