### ISSUE TITLE
vt partition error with GATK vcf

### ISSUE THREAD

**Issue by MarisaMiller** [atks/vt#82]
Hi Adrian,

I encountered an issue where vcf files generated by GATK throw an error when I try to compare them to other vcf files with vcf partition: `[E:bcf_synced_reader.cpp:599 fill_buffer] VCF file not in order`

This error happens if I compare two GATk files to each other, or a GATK file to a FreeBayes file, but not if I compare two FreeBayes files. The reference genomes used to generate the files was the same so the contigs are the same in all headers. 

Here are links to an example FreeBayes and GATK file:
https://s3.msi.umn.edu/vcf_files/2015_isolates.freebayes.filter_for_compare.sites.vcf
https://s3.msi.umn.edu/vcf_files/2015_isolates.gatk.filter.sites.vcf

Any input you have would be greatly appreciated!

Thanks,
Marisa

**Comment by atks** [comment]
@MarisaMiller 

Hi Marisa, you need to sort the files first.  Your GATK VCF file is not sorted.

You can detect this by running vt validate gatk.vcf
=>
[validate.cpp:144 validate] UNORDERED: 000001F: 46389 after 46408
[validate.cpp:144 validate] UNORDERED: 000004F: 317734 after 317745
[validate.cpp:144 validate] UNORDERED: 000007F: 730742 after 730752
[validate.cpp:144 validate] UNORDERED: 000008F: 649704 after 649721
.....

do:  vt sort gatk.vcf -o sorted.gatk.vcf -m local
then try vt partition again.

**Comment by MarisaMiller** [comment]
Hi Adrian,

Thanks so much for the tip! That worked beautifully. 

Thanks,
Marisa
