### ISSUE TITLE
option missing to configure installation directory from source

### ISSUE THREAD

**Issue by mercedes-colomar** [atks/vt#86]
There does not appear to be a way to specify a target directory for installation when building from source. Any suggestions?

**Comment by atks** [comment]
@mercedes-colomar 

The vt binary works by itself, just copy the binary to the directory you want to put it in.

**Comment by atks** [comment]
@mercedes-colomar 

it just creates a binary named vt in the source directory from where you run make.  

you can also use the github way as described in https://genome.sph.umich.edu/wiki/Vt#Installation

there is no make install command.

**Comment by mercedes-colomar** [comment]
@atks 

Thanks that works. We have a requirement to build a specific version of the app so the github method is not suitable.
