### ISSUE TITLE
Decomposition of multi-allellic loci lose Number=G type INFO fields

### ISSUE THREAD

**Issue by mmoisse** [atks/vt#87]
I noticed that when you decompose multi-allellic variants the lose all INFO fields of type Number=G

    ##INFO=<ID=GC_Male,Number=G,Type=Integer,Description="Count of Male individuals for each genotype">
    wget https://storage.googleapis.com/gnomad-public/release/2.0.2/vcf/genomes/gnomad.genomes.r2.0.2.sites.chr15.vcf.bgz.tbi
    wget https://storage.googleapis.com/gnomad-public/release/2.0.2/vcf/genomes/gnomad.genomes.r2.0.2.sites.chr15.vcf.bgz
    tabix -h gnomad.genomes.r2.0.2.sites.chr15.vcf.bgz 15:72639383-72639383  | grep GC_Male
    tabix -h gnomad.genomes.r2.0.2.sites.chr15.vcf.bgz 15:72639383-72639383 | ~/software/vt/current/vt decompose -s - 2>/dev/null | grep GC_Male

**Comment by atks** [comment]
@mmoisse - I can't download the file by wget, what do you use in this case for google storage?

**Comment by mmoisse** [comment]
It was the wrong URL I updated it now.

**Comment by atks** [comment]
@mmoisse - it used to work correctly, I haven't touched this code for a long time so it might be due to changes in htslib.

**Comment by atks** [comment]
@mmoisse - could you pull it and check it, it was actually a bug that had never been fixed.
