### ISSUE TITLE
smart decomposition does not export AD for multiallelic variant

### ISSUE THREAD

**Issue by wangshu84** [atks/vt#88]
Hello, I used smart decomposition for getting AD and GQ. However, decomposed output have "." for all multiallelic variants. It is VCFv4.2 with FORMAT=<ID=AD,Number=R...

e.g. For a multiallelic variant
    OLD_MULTIALLELIC=chr1:115256325:A/G/T	GT:AD:DP:GQ:PGT:PID:PL 0/0:.:15:45:.:.:0,45,632,45

if not multiallelic:
    GT:AD:DP:GQ:PL  0/0:15,0,0:15:45:0,45,648,45,648,648

1).Wonder is there a way to get all AD information for all alt alleles. 
2). For multiallelic situation, e.g. 2 alt alleles, is there a way to write entry for new genotype GT=1/2

Thank you!

**Comment by atks** [comment]
@wangshu84 

Can you give me an example VCF to work with?

**Comment by wangshu84** [comment]
@atks  Attached is a test.vcf file. It has extension .txt just for uploading. Thank you! 
[vt_test.vcf.txt](https://github.com/atks/vt/files/2125381/vt_test.vcf.txt)

**Comment by wangshu84** [comment]
@atks unfortunately without -s option, it does not output AD neither.

**Comment by atks** [comment]
@wangshu84 - apologies for the delay, I can only respond on this around next week.

**Comment by wangshu84** [comment]
@atks

**Comment by wangshu84** [comment]
@atks looks like header INFO field is the reason causing missing AD for multiallelic variants.
If change format of AD field to "Number=." (input vcf has "Number=R"), the smart decompose will output AD values. 
The input vcf is by GATK_3.7

**Comment by atks** [comment]
@wangshu84 
apologies about this, I should have spotted it much earlier.
