### ISSUE TITLE
Consecutive SNPs

### ISSUE THREAD

**Issue by nurmians** [atks/vt#98]
At least GATK4/Mutect2 calls two consecutive SNPs as:

CHROM|COORD|ID|REF|ALT
--------|---------|--|---|------
chr2|110666292|      .|       AC|      GT

would be nice if vt normalize was able to split it into:

CHROM|COORD|ID|REF|ALT
--------|---------|--|---|------
chr2|    110666292    |   .    |   A    |  G
chr2 |   110666293  |     .|       C |     T

I had to do this with another script after normalization to be able to compare the calls.

**Comment by atks** [comment]
you can use the command blocksub
